package com.api.measureconverter.seed;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;

import com.api.measureconverter.controller.UserController;
import com.api.measureconverter.model.ConverterEntity;
import com.api.measureconverter.repositories.ConverterRepository;
import com.api.measureconverter.repositories.UserRepository;
import com.api.measureconverter.utils.dto.RegisterDto;
import com.api.measureconverter.utils.dto.UserDto;
import com.api.measureconverter.utils.enums.ConversionCategories;
import com.api.measureconverter.utils.enums.Roles;
import com.api.measureconverter.utils.reponse.Response;

import jakarta.transaction.Transactional;

@Component
public class DataInitializer implements CommandLineRunner {

        @Autowired
        ConverterRepository conversionRepository;

        @Autowired
        UserRepository userRepository;

        @Autowired
        UserController userController;

        @Value("${ADMIN_USERNAME}")
        private String username;

        @Value("${ADMIN_EMAIL}")
        private String adminEmail;

        @Value("${ADMIN_PASSWORD}")
        private String adminPassword;

        @Override
        @Transactional
        public void run(String... args) throws Exception {
                List<ConverterEntity> conversions = List.of(
                                // Length conversions
                                createConversion("meter", "kilometer", BigDecimal.valueOf(0.001),
                                                ConversionCategories.LENGTH),
                                createConversion("kilometer", "meter", BigDecimal.valueOf(1000),
                                                ConversionCategories.LENGTH),
                                createConversion("meter", "centimeter", BigDecimal.valueOf(100),
                                                ConversionCategories.LENGTH),
                                createConversion("centimeter", "meter", BigDecimal.valueOf(0.01),
                                                ConversionCategories.LENGTH),
                                createConversion("meter", "millimeter", BigDecimal.valueOf(1000),
                                                ConversionCategories.LENGTH),
                                createConversion("millimeter", "meter", BigDecimal.valueOf(0.001),
                                                ConversionCategories.LENGTH),
                                createConversion("meter", "inch", BigDecimal.valueOf(39.3701),
                                                ConversionCategories.LENGTH),
                                createConversion("inch", "meter", BigDecimal.valueOf(0.0254),
                                                ConversionCategories.LENGTH),
                                createConversion("meter", "foot", BigDecimal.valueOf(3.28084),
                                                ConversionCategories.LENGTH),
                                createConversion("foot", "meter", BigDecimal.valueOf(0.3048),
                                                ConversionCategories.LENGTH),
                                createConversion("meter", "yard", BigDecimal.valueOf(1.09361),
                                                ConversionCategories.LENGTH),
                                createConversion("yard", "meter", BigDecimal.valueOf(0.9144),
                                                ConversionCategories.LENGTH),
                                createConversion("meter", "mile", BigDecimal.valueOf(0.000621371),
                                                ConversionCategories.LENGTH),
                                createConversion("mile", "meter", BigDecimal.valueOf(1609.34),
                                                ConversionCategories.LENGTH),
                                createConversion("kilometer", "centimeter", BigDecimal.valueOf(100000),
                                                ConversionCategories.LENGTH),
                                createConversion("centimeter", "kilometer", BigDecimal.valueOf(0.00001),
                                                ConversionCategories.LENGTH),
                                createConversion("kilometer", "millimeter", BigDecimal.valueOf(1000000),
                                                ConversionCategories.LENGTH),
                                createConversion("millimeter", "kilometer", BigDecimal.valueOf(0.000001),
                                                ConversionCategories.LENGTH),
                                createConversion("kilometer", "inch", BigDecimal.valueOf(39370.1),
                                                ConversionCategories.LENGTH),
                                createConversion("inch", "kilometer", BigDecimal.valueOf(0.0000254),
                                                ConversionCategories.LENGTH),
                                createConversion("kilometer", "foot", BigDecimal.valueOf(3280.84),
                                                ConversionCategories.LENGTH),
                                createConversion("foot", "kilometer", BigDecimal.valueOf(0.0003048),
                                                ConversionCategories.LENGTH),
                                createConversion("kilometer", "yard", BigDecimal.valueOf(1093.61),
                                                ConversionCategories.LENGTH),
                                createConversion("yard", "kilometer", BigDecimal.valueOf(0.0009144),
                                                ConversionCategories.LENGTH),
                                createConversion("kilometer", "mile", BigDecimal.valueOf(0.621371),
                                                ConversionCategories.LENGTH),
                                createConversion("mile", "kilometer", BigDecimal.valueOf(1.60934),
                                                ConversionCategories.LENGTH),
                                createConversion("centimeter", "millimeter", BigDecimal.valueOf(10),
                                                ConversionCategories.LENGTH),
                                createConversion("millimeter", "centimeter", BigDecimal.valueOf(0.1),
                                                ConversionCategories.LENGTH),
                                createConversion("centimeter", "inch", BigDecimal.valueOf(0.393701),
                                                ConversionCategories.LENGTH),
                                createConversion("inch", "centimeter", BigDecimal.valueOf(2.54),
                                                ConversionCategories.LENGTH),
                                createConversion("centimeter", "foot", BigDecimal.valueOf(0.0328084),
                                                ConversionCategories.LENGTH),
                                createConversion("foot", "centimeter", BigDecimal.valueOf(30.48),
                                                ConversionCategories.LENGTH),
                                createConversion("centimeter", "yard", BigDecimal.valueOf(0.0109361),
                                                ConversionCategories.LENGTH),
                                createConversion("yard", "centimeter", BigDecimal.valueOf(91.44),
                                                ConversionCategories.LENGTH),
                                createConversion("centimeter", "mile", BigDecimal.valueOf(0.00000621371),
                                                ConversionCategories.LENGTH),
                                createConversion("mile", "centimeter", BigDecimal.valueOf(160934),
                                                ConversionCategories.LENGTH),
                                createConversion("millimeter", "inch", BigDecimal.valueOf(0.0393701),
                                                ConversionCategories.LENGTH),
                                createConversion("inch", "millimeter", BigDecimal.valueOf(25.4),
                                                ConversionCategories.LENGTH),
                                createConversion("millimeter", "foot", BigDecimal.valueOf(0.00328084),
                                                ConversionCategories.LENGTH),
                                createConversion("foot", "millimeter", BigDecimal.valueOf(304.8),
                                                ConversionCategories.LENGTH),
                                createConversion("millimeter", "yard", BigDecimal.valueOf(0.00109361),
                                                ConversionCategories.LENGTH),
                                createConversion("yard", "millimeter", BigDecimal.valueOf(914.4),
                                                ConversionCategories.LENGTH),
                                createConversion("millimeter", "mile", BigDecimal.valueOf(0.000000621371),
                                                ConversionCategories.LENGTH),
                                createConversion("mile", "millimeter", BigDecimal.valueOf(1609340),
                                                ConversionCategories.LENGTH),
                                createConversion("inch", "foot", BigDecimal.valueOf(0.0833333),
                                                ConversionCategories.LENGTH),
                                createConversion("foot", "inch", BigDecimal.valueOf(12), ConversionCategories.LENGTH),
                                createConversion("inch", "yard", BigDecimal.valueOf(0.0277778),
                                                ConversionCategories.LENGTH),
                                createConversion("yard", "inch", BigDecimal.valueOf(36), ConversionCategories.LENGTH),
                                createConversion("inch", "mile", BigDecimal.valueOf(0.0000157828),
                                                ConversionCategories.LENGTH),
                                createConversion("mile", "inch", BigDecimal.valueOf(63360),
                                                ConversionCategories.LENGTH),
                                createConversion("foot", "yard", BigDecimal.valueOf(0.333333),
                                                ConversionCategories.LENGTH),
                                createConversion("yard", "foot", BigDecimal.valueOf(3), ConversionCategories.LENGTH),
                                createConversion("foot", "mile", BigDecimal.valueOf(0.000189394),
                                                ConversionCategories.LENGTH),
                                createConversion("mile", "foot", BigDecimal.valueOf(5280), ConversionCategories.LENGTH),
                                createConversion("yard", "mile", BigDecimal.valueOf(0.000568182),
                                                ConversionCategories.LENGTH),
                                createConversion("mile", "yard", BigDecimal.valueOf(1760), ConversionCategories.LENGTH),

                                // Weight conversions
                                createConversion("gram", "kilogram", BigDecimal.valueOf(0.001),
                                                ConversionCategories.WEIGHT),
                                createConversion("gram", "pound", BigDecimal.valueOf(0.00220462),
                                                ConversionCategories.WEIGHT),
                                createConversion("gram", "ton", BigDecimal.valueOf(0.000001),
                                                ConversionCategories.WEIGHT),
                                createConversion("gram", "ounce", BigDecimal.valueOf(0.035274),
                                                ConversionCategories.WEIGHT),
                                createConversion("kilogram", "gram", BigDecimal.valueOf(1000),
                                                ConversionCategories.WEIGHT),
                                createConversion("kilogram", "pound", BigDecimal.valueOf(2.20462),
                                                ConversionCategories.WEIGHT),
                                createConversion("kilogram", "ton", BigDecimal.valueOf(0.001),
                                                ConversionCategories.WEIGHT),
                                createConversion("kilogram", "ounce", BigDecimal.valueOf(35.274),
                                                ConversionCategories.WEIGHT),
                                createConversion("pound", "kilogram", BigDecimal.valueOf(0.453592),
                                                ConversionCategories.WEIGHT),
                                createConversion("ounce", "gram", BigDecimal.valueOf(28.3495),
                                                ConversionCategories.WEIGHT),
                                createConversion("ounce", "pound", BigDecimal.valueOf(0.0625),
                                                ConversionCategories.WEIGHT),
                                createConversion("pound", "ounce", BigDecimal.valueOf(16), ConversionCategories.WEIGHT),
                                createConversion("ton", "kilogram", BigDecimal.valueOf(1000),
                                                ConversionCategories.WEIGHT),
                                createConversion("pound", "gram", BigDecimal.valueOf(453.592),
                                                ConversionCategories.WEIGHT),
                                createConversion("ounce", "gram", BigDecimal.valueOf(28.3495),
                                                ConversionCategories.WEIGHT),
                                createConversion("ounce", "kilogram", BigDecimal.valueOf(0.0283495),
                                                ConversionCategories.WEIGHT),
                                createConversion("ton", "gram", BigDecimal.valueOf(1000000),
                                                ConversionCategories.WEIGHT),
                                createConversion("ton", "pound", BigDecimal.valueOf(2204.62),
                                                ConversionCategories.WEIGHT),
                                createConversion("pound", "ton", BigDecimal.valueOf(0.000453592),
                                                ConversionCategories.WEIGHT),
                                createConversion("ton", "ounce", BigDecimal.valueOf(35274),
                                                ConversionCategories.WEIGHT),
                                createConversion("ounce", "ton", BigDecimal.valueOf(0.0000283495),
                                                ConversionCategories.WEIGHT),

                                // Data size conversions
                                createConversion("bit", "byte", BigDecimal.valueOf(0.125),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("byte", "bit", BigDecimal.valueOf(8), ConversionCategories.DATA_SIZE),
                                createConversion("byte", "kilobyte", BigDecimal.valueOf(0.001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("kilobyte", "byte", BigDecimal.valueOf(1000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("kilobyte", "megabyte", BigDecimal.valueOf(0.001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("megabyte", "kilobyte", BigDecimal.valueOf(1000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("megabyte", "gigabyte", BigDecimal.valueOf(0.001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabyte", "megabyte", BigDecimal.valueOf(1000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabyte", "terabyte", BigDecimal.valueOf(0.001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("terabyte", "gigabyte", BigDecimal.valueOf(1000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabit", "megabyte", BigDecimal.valueOf(125),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("megabyte", "gigabit", BigDecimal.valueOf(0.008),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("bit", "kilobyte", BigDecimal.valueOf(0.000125),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("kilobyte", "bit", BigDecimal.valueOf(8000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("bit", "megabyte", BigDecimal.valueOf(0.000000125),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("megabyte", "bit", BigDecimal.valueOf(8000000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("bit", "gigabyte", BigDecimal.valueOf(0.000000000125),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabyte", "bit", BigDecimal.valueOf(8000000000L),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("bit", "terabyte", BigDecimal.valueOf(0.000000000000125),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("terabyte", "bit", BigDecimal.valueOf(8000000000000L),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("byte", "megabyte", BigDecimal.valueOf(0.000001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("megabyte", "byte", BigDecimal.valueOf(1000000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("byte", "gigabyte", BigDecimal.valueOf(0.000000001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabyte", "byte", BigDecimal.valueOf(1000000000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("byte", "terabyte", BigDecimal.valueOf(0.000000000001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("terabyte", "byte", BigDecimal.valueOf(1000000000000L),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("kilobyte", "gigabyte", BigDecimal.valueOf(0.000001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabyte", "kilobyte", BigDecimal.valueOf(1000000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("kilobyte", "terabyte", BigDecimal.valueOf(0.000000001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("terabyte", "kilobyte", BigDecimal.valueOf(1000000000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("megabyte", "terabyte", BigDecimal.valueOf(0.000001),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("terabyte", "megabyte", BigDecimal.valueOf(1000000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabit", "kilobyte", BigDecimal.valueOf(125000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("kilobyte", "gigabit", BigDecimal.valueOf(0.000008),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabit", "byte", BigDecimal.valueOf(125000000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("byte", "gigabit", BigDecimal.valueOf(0.000000008),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("gigabit", "bit", BigDecimal.valueOf(1000000000),
                                                ConversionCategories.DATA_SIZE),
                                createConversion("bit", "gigabit", BigDecimal.valueOf(0.000000001),
                                                ConversionCategories.DATA_SIZE),

                                // Area conversions
                                createConversion("square_meter", "square_kilometer", BigDecimal.valueOf(0.000001),
                                                ConversionCategories.AREA),
                                createConversion("square_kilometer", "square_meter", BigDecimal.valueOf(1000000),
                                                ConversionCategories.AREA),
                                createConversion("acre", "square_meter", BigDecimal.valueOf(4046.86),
                                                ConversionCategories.AREA),
                                createConversion("square_meter", "acre", BigDecimal.valueOf(0.000247105),
                                                ConversionCategories.AREA),
                                createConversion("square_foot", "square_meter", BigDecimal.valueOf(0.092903),
                                                ConversionCategories.AREA),
                                createConversion("square_meter", "square_foot", BigDecimal.valueOf(10.7639),
                                                ConversionCategories.AREA),
                                createConversion("hectare", "square_meter", BigDecimal.valueOf(10000),
                                                ConversionCategories.AREA),
                                createConversion("square_meter", "hectare", BigDecimal.valueOf(0.0001),
                                                ConversionCategories.AREA),
                                createConversion("square_foot", "square_yard", BigDecimal.valueOf(0.111111),
                                                ConversionCategories.AREA),
                                createConversion("square_yard", "square_foot", BigDecimal.valueOf(9),
                                                ConversionCategories.AREA),
                                createConversion("square_kilometer", "acre", BigDecimal.valueOf(247.105),
                                                ConversionCategories.AREA),
                                createConversion("acre", "square_kilometer", BigDecimal.valueOf(0.00404686),
                                                ConversionCategories.AREA),
                                createConversion("square_kilometer", "square_foot", BigDecimal.valueOf(10763910.4),
                                                ConversionCategories.AREA),
                                createConversion("square_foot", "square_kilometer", BigDecimal.valueOf(0.000000092903),
                                                ConversionCategories.AREA),
                                createConversion("square_kilometer", "square_yard", BigDecimal.valueOf(1195990.05),
                                                ConversionCategories.AREA),
                                createConversion("square_yard", "square_kilometer", BigDecimal.valueOf(0.000000836127),
                                                ConversionCategories.AREA),
                                createConversion("square_kilometer", "hectare", BigDecimal.valueOf(100),
                                                ConversionCategories.AREA),
                                createConversion("hectare", "square_kilometer", BigDecimal.valueOf(0.01),
                                                ConversionCategories.AREA),
                                createConversion("acre", "square_foot", BigDecimal.valueOf(43560),
                                                ConversionCategories.AREA),
                                createConversion("square_foot", "acre", BigDecimal.valueOf(0.0000229568),
                                                ConversionCategories.AREA),
                                createConversion("acre", "square_yard", BigDecimal.valueOf(4840),
                                                ConversionCategories.AREA),
                                createConversion("square_yard", "acre", BigDecimal.valueOf(0.000206612),
                                                ConversionCategories.AREA),
                                createConversion("acre", "hectare", BigDecimal.valueOf(0.404686),
                                                ConversionCategories.AREA),
                                createConversion("hectare", "acre", BigDecimal.valueOf(2.47105),
                                                ConversionCategories.AREA),
                                createConversion("square_meter", "square_yard", BigDecimal.valueOf(1.19599),
                                                ConversionCategories.AREA),
                                createConversion("square_yard", "square_meter", BigDecimal.valueOf(0.836127),
                                                ConversionCategories.AREA),
                                createConversion("square_foot", "hectare", BigDecimal.valueOf(0.0000092903),
                                                ConversionCategories.AREA),
                                createConversion("hectare", "square_foot", BigDecimal.valueOf(107639),
                                                ConversionCategories.AREA),
                                createConversion("square_yard", "hectare", BigDecimal.valueOf(0.0000836127),
                                                ConversionCategories.AREA),
                                createConversion("hectare", "square_yard", BigDecimal.valueOf(11959.9),
                                                ConversionCategories.AREA),

                                // Volume conversions
                                createConversion("liter", "milliliter", BigDecimal.valueOf(1000),
                                                ConversionCategories.VOLUME),
                                createConversion("milliliter", "liter", BigDecimal.valueOf(0.001),
                                                ConversionCategories.VOLUME),
                                createConversion("gallon", "liter", BigDecimal.valueOf(3.78541),
                                                ConversionCategories.VOLUME),
                                createConversion("liter", "gallon", BigDecimal.valueOf(0.264172),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_meter", "liter", BigDecimal.valueOf(1000),
                                                ConversionCategories.VOLUME),
                                createConversion("liter", "cubic_meter", BigDecimal.valueOf(0.001),
                                                ConversionCategories.VOLUME),
                                createConversion("cup", "liter", BigDecimal.valueOf(0.236588),
                                                ConversionCategories.VOLUME),
                                createConversion("liter", "cup", BigDecimal.valueOf(4.22675),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_foot", "cubic_meter", BigDecimal.valueOf(0.0283168),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_meter", "cubic_foot", BigDecimal.valueOf(35.3147),
                                                ConversionCategories.VOLUME),
                                createConversion("milliliter", "gallon", BigDecimal.valueOf(0.000264172),
                                                ConversionCategories.VOLUME),
                                createConversion("gallon", "milliliter", BigDecimal.valueOf(3785.41),
                                                ConversionCategories.VOLUME),
                                createConversion("milliliter", "cubic_meter", BigDecimal.valueOf(0.000001),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_meter", "milliliter", BigDecimal.valueOf(1000000),
                                                ConversionCategories.VOLUME),
                                createConversion("milliliter", "cup", BigDecimal.valueOf(0.00422675),
                                                ConversionCategories.VOLUME),
                                createConversion("cup", "milliliter", BigDecimal.valueOf(236.588),
                                                ConversionCategories.VOLUME),
                                createConversion("gallon", "cubic_meter", BigDecimal.valueOf(0.00378541),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_meter", "gallon", BigDecimal.valueOf(264.172),
                                                ConversionCategories.VOLUME),
                                createConversion("gallon", "cup", BigDecimal.valueOf(16), ConversionCategories.VOLUME),
                                createConversion("cup", "gallon", BigDecimal.valueOf(0.0625),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_foot", "liter", BigDecimal.valueOf(28.3168),
                                                ConversionCategories.VOLUME),
                                createConversion("liter", "cubic_foot", BigDecimal.valueOf(0.0353147),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_foot", "milliliter", BigDecimal.valueOf(28316.8),
                                                ConversionCategories.VOLUME),
                                createConversion("milliliter", "cubic_foot", BigDecimal.valueOf(0.0000353147),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_foot", "gallon", BigDecimal.valueOf(7.48052),
                                                ConversionCategories.VOLUME),
                                createConversion("gallon", "cubic_foot", BigDecimal.valueOf(0.133681),
                                                ConversionCategories.VOLUME),
                                createConversion("cubic_foot", "cup", BigDecimal.valueOf(119.688),
                                                ConversionCategories.VOLUME),
                                createConversion("cup", "cubic_foot", BigDecimal.valueOf(0.00835503),
                                                ConversionCategories.VOLUME),

                                // Temperature conversions (handled in logic due to offsets)
                                createConversion("celsius", "fahrenheit", BigDecimal.valueOf(1.8),
                                                ConversionCategories.TEMPERATURE),
                                createConversion("celsius", "kelvin", BigDecimal.valueOf(1),
                                                ConversionCategories.TEMPERATURE),
                                createConversion("fahrenheit", "celsius", BigDecimal.valueOf(0.5556),
                                                ConversionCategories.TEMPERATURE),
                                createConversion("fahrenheit", "kelvin", BigDecimal.valueOf(0.5556),
                                                ConversionCategories.TEMPERATURE),
                                createConversion("kelvin", "celsius", BigDecimal.valueOf(1),
                                                ConversionCategories.TEMPERATURE),
                                createConversion("kelvin", "fahrenheit", BigDecimal.valueOf(1.8),
                                                ConversionCategories.TEMPERATURE),

                                // Time conversions
                                createConversion("second", "minute", BigDecimal.valueOf(0.0166667),
                                                ConversionCategories.TIME),
                                createConversion("minute", "second", BigDecimal.valueOf(60), ConversionCategories.TIME),
                                createConversion("hour", "minute", BigDecimal.valueOf(60), ConversionCategories.TIME),
                                createConversion("minute", "hour", BigDecimal.valueOf(0.0166667),
                                                ConversionCategories.TIME),
                                createConversion("day", "hour", BigDecimal.valueOf(24), ConversionCategories.TIME),
                                createConversion("hour", "day", BigDecimal.valueOf(0.0416667),
                                                ConversionCategories.TIME),
                                createConversion("week", "day", BigDecimal.valueOf(7), ConversionCategories.TIME),
                                createConversion("day", "week", BigDecimal.valueOf(0.142857),
                                                ConversionCategories.TIME),
                                createConversion("millisecond", "second", BigDecimal.valueOf(0.001),
                                                ConversionCategories.TIME),
                                createConversion("second", "millisecond", BigDecimal.valueOf(1000),
                                                ConversionCategories.TIME),
                                createConversion("month", "day", BigDecimal.valueOf(30.44), ConversionCategories.TIME), // Approximate
                                createConversion("year", "day", BigDecimal.valueOf(365.25), ConversionCategories.TIME), // Approximate
                                createConversion("second", "hour", BigDecimal.valueOf(0.000277778),
                                                ConversionCategories.TIME),
                                createConversion("hour", "second", BigDecimal.valueOf(3600), ConversionCategories.TIME),
                                createConversion("second", "day", BigDecimal.valueOf(0.0000115741),
                                                ConversionCategories.TIME),
                                createConversion("day", "second", BigDecimal.valueOf(86400), ConversionCategories.TIME),
                                createConversion("second", "week", BigDecimal.valueOf(0.00000165344),
                                                ConversionCategories.TIME),
                                createConversion("week", "second", BigDecimal.valueOf(604800),
                                                ConversionCategories.TIME),
                                createConversion("second", "month", BigDecimal.valueOf(0.000000380517),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("month", "second", BigDecimal.valueOf(2628000),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("second", "year", BigDecimal.valueOf(0.0000000317098),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("year", "second", BigDecimal.valueOf(31536000),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("minute", "day", BigDecimal.valueOf(0.000694444),
                                                ConversionCategories.TIME),
                                createConversion("day", "minute", BigDecimal.valueOf(1440), ConversionCategories.TIME),
                                createConversion("minute", "week", BigDecimal.valueOf(0.0000992063),
                                                ConversionCategories.TIME),
                                createConversion("week", "minute", BigDecimal.valueOf(10080),
                                                ConversionCategories.TIME),
                                createConversion("minute", "month", BigDecimal.valueOf(0.0000228311),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("month", "minute", BigDecimal.valueOf(43800),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("minute", "year", BigDecimal.valueOf(0.00000190129),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("year", "minute", BigDecimal.valueOf(525600),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("hour", "week", BigDecimal.valueOf(0.00595238),
                                                ConversionCategories.TIME),
                                createConversion("week", "hour", BigDecimal.valueOf(168), ConversionCategories.TIME),
                                createConversion("hour", "month", BigDecimal.valueOf(0.00136986),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("month", "hour", BigDecimal.valueOf(730), ConversionCategories.TIME), // Approximate
                                createConversion("hour", "year", BigDecimal.valueOf(0.000114155),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("year", "hour", BigDecimal.valueOf(8760), ConversionCategories.TIME), // Approximate
                                createConversion("day", "month", BigDecimal.valueOf(0.0328767),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("month", "day", BigDecimal.valueOf(30.44), ConversionCategories.TIME), // Approximate
                                createConversion("day", "year", BigDecimal.valueOf(0.00273791),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("year", "day", BigDecimal.valueOf(365.25), ConversionCategories.TIME), // Approximate
                                createConversion("week", "month", BigDecimal.valueOf(0.230137),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("month", "week", BigDecimal.valueOf(4.34524),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("week", "year", BigDecimal.valueOf(0.0191781),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("year", "week", BigDecimal.valueOf(52.1786),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("millisecond", "minute", BigDecimal.valueOf(0.0000166667),
                                                ConversionCategories.TIME),
                                createConversion("minute", "millisecond", BigDecimal.valueOf(60000),
                                                ConversionCategories.TIME),
                                createConversion("millisecond", "hour", BigDecimal.valueOf(0.000000277778),
                                                ConversionCategories.TIME),
                                createConversion("hour", "millisecond", BigDecimal.valueOf(3600000),
                                                ConversionCategories.TIME),
                                createConversion("millisecond", "day", BigDecimal.valueOf(0.0000000115741),
                                                ConversionCategories.TIME),
                                createConversion("day", "millisecond", BigDecimal.valueOf(86400000),
                                                ConversionCategories.TIME),
                                createConversion("millisecond", "week", BigDecimal.valueOf(0.00000000165344),
                                                ConversionCategories.TIME),
                                createConversion("week", "millisecond", BigDecimal.valueOf(604800000),
                                                ConversionCategories.TIME),
                                createConversion("millisecond", "month", BigDecimal.valueOf(0.000000000380517),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("month", "millisecond", BigDecimal.valueOf(2628000000L),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("millisecond", "year", BigDecimal.valueOf(0.0000000000317098),
                                                ConversionCategories.TIME), // Approximate
                                createConversion("year", "millisecond", BigDecimal.valueOf(31536000000L),
                                                ConversionCategories.TIME), // Approximate

                                // Speed conversions
                                createConversion("meter_per_second", "kilometer_per_hour", BigDecimal.valueOf(3.6),
                                                ConversionCategories.SPEED),
                                createConversion("kilometer_per_hour", "meter_per_second", BigDecimal.valueOf(0.277778),
                                                ConversionCategories.SPEED),
                                createConversion("mile_per_hour", "kilometer_per_hour", BigDecimal.valueOf(1.60934),
                                                ConversionCategories.SPEED),
                                createConversion("kilometer_per_hour", "mile_per_hour", BigDecimal.valueOf(0.621371),
                                                ConversionCategories.SPEED),
                                createConversion("knot", "mile_per_hour", BigDecimal.valueOf(1.15078),
                                                ConversionCategories.SPEED),
                                createConversion("mile_per_hour", "knot", BigDecimal.valueOf(0.868976),
                                                ConversionCategories.SPEED),
                                createConversion("foot_per_second", "meter_per_second", BigDecimal.valueOf(0.3048),
                                                ConversionCategories.SPEED),
                                createConversion("meter_per_second", "foot_per_second", BigDecimal.valueOf(3.28084),
                                                ConversionCategories.SPEED),
                                createConversion("mach", "kilometer_per_hour", BigDecimal.valueOf(1225.08),
                                                ConversionCategories.SPEED),
                                createConversion("kilometer_per_hour", "mach", BigDecimal.valueOf(0.000816273),
                                                ConversionCategories.SPEED),
                                createConversion("meter_per_second", "mile_per_hour", BigDecimal.valueOf(2.23694),
                                                ConversionCategories.SPEED),
                                createConversion("mile_per_hour", "meter_per_second", BigDecimal.valueOf(0.44704),
                                                ConversionCategories.SPEED),
                                createConversion("meter_per_second", "knot", BigDecimal.valueOf(1.94384),
                                                ConversionCategories.SPEED),
                                createConversion("knot", "meter_per_second", BigDecimal.valueOf(0.514444),
                                                ConversionCategories.SPEED),
                                createConversion("meter_per_second", "mach", BigDecimal.valueOf(0.00293858),
                                                ConversionCategories.SPEED),
                                createConversion("mach", "meter_per_second", BigDecimal.valueOf(340.29),
                                                ConversionCategories.SPEED),
                                createConversion("kilometer_per_hour", "foot_per_second", BigDecimal.valueOf(0.911344),
                                                ConversionCategories.SPEED),
                                createConversion("foot_per_second", "kilometer_per_hour", BigDecimal.valueOf(1.09728),
                                                ConversionCategories.SPEED),
                                createConversion("mile_per_hour", "foot_per_second", BigDecimal.valueOf(1.46667),
                                                ConversionCategories.SPEED),
                                createConversion("foot_per_second", "mile_per_hour", BigDecimal.valueOf(0.681818),
                                                ConversionCategories.SPEED),
                                createConversion("knot", "kilometer_per_hour", BigDecimal.valueOf(1.852),
                                                ConversionCategories.SPEED),
                                createConversion("kilometer_per_hour", "knot", BigDecimal.valueOf(0.539957),
                                                ConversionCategories.SPEED),
                                createConversion("knot", "mach", BigDecimal.valueOf(0.00149725),
                                                ConversionCategories.SPEED),
                                createConversion("mach", "knot", BigDecimal.valueOf(667.919),
                                                ConversionCategories.SPEED),
                                createConversion("mile_per_hour", "mach", BigDecimal.valueOf(0.00130332),
                                                ConversionCategories.SPEED),
                                createConversion("mach", "mile_per_hour", BigDecimal.valueOf(767.269),
                                                ConversionCategories.SPEED),
                                createConversion("foot_per_second", "mach", BigDecimal.valueOf(0.00293858),
                                                ConversionCategories.SPEED),
                                createConversion("mach", "foot_per_second", BigDecimal.valueOf(1116.47),
                                                ConversionCategories.SPEED),

                                // Pressure conversions
                                createConversion("pascal", "bar", BigDecimal.valueOf(0.00001),
                                                ConversionCategories.PRESSURE),
                                createConversion("bar", "pascal", BigDecimal.valueOf(100000),
                                                ConversionCategories.PRESSURE),
                                createConversion("psi", "bar", BigDecimal.valueOf(0.0689476),
                                                ConversionCategories.PRESSURE),
                                createConversion("bar", "psi", BigDecimal.valueOf(14.5038),
                                                ConversionCategories.PRESSURE),
                                createConversion("atmosphere", "pascal", BigDecimal.valueOf(101325),
                                                ConversionCategories.PRESSURE),
                                createConversion("pascal", "atmosphere", BigDecimal.valueOf(0.00000986923),
                                                ConversionCategories.PRESSURE),
                                createConversion("millimeter_of_mercury", "pascal", BigDecimal.valueOf(133.322),
                                                ConversionCategories.PRESSURE),
                                createConversion("pascal", "millimeter_of_mercury", BigDecimal.valueOf(0.00750062),
                                                ConversionCategories.PRESSURE),
                                createConversion("torr", "pascal", BigDecimal.valueOf(133.322),
                                                ConversionCategories.PRESSURE),
                                createConversion("pascal", "torr", BigDecimal.valueOf(0.00750062),
                                                ConversionCategories.PRESSURE),
                                createConversion("bar", "atmosphere", BigDecimal.valueOf(0.986923),
                                                ConversionCategories.PRESSURE),
                                createConversion("atmosphere", "bar", BigDecimal.valueOf(1.01325),
                                                ConversionCategories.PRESSURE),
                                createConversion("psi", "pascal", BigDecimal.valueOf(6894.76),
                                                ConversionCategories.PRESSURE),
                                createConversion("pascal", "psi", BigDecimal.valueOf(0.000145038),
                                                ConversionCategories.PRESSURE),
                                createConversion("psi", "atmosphere", BigDecimal.valueOf(0.0680459),
                                                ConversionCategories.PRESSURE),
                                createConversion("atmosphere", "psi", BigDecimal.valueOf(14.696),
                                                ConversionCategories.PRESSURE),
                                createConversion("psi", "millimeter_of_mercury", BigDecimal.valueOf(51.7149),
                                                ConversionCategories.PRESSURE),
                                createConversion("millimeter_of_mercury", "psi", BigDecimal.valueOf(0.0193368),
                                                ConversionCategories.PRESSURE),
                                createConversion("psi", "torr", BigDecimal.valueOf(51.7149),
                                                ConversionCategories.PRESSURE),
                                createConversion("torr", "psi", BigDecimal.valueOf(0.0193368),
                                                ConversionCategories.PRESSURE),
                                createConversion("bar", "millimeter_of_mercury", BigDecimal.valueOf(750.062),
                                                ConversionCategories.PRESSURE),
                                createConversion("millimeter_of_mercury", "bar", BigDecimal.valueOf(0.00133322),
                                                ConversionCategories.PRESSURE),
                                createConversion("bar", "torr", BigDecimal.valueOf(750.062),
                                                ConversionCategories.PRESSURE),
                                createConversion("torr", "bar", BigDecimal.valueOf(0.00133322),
                                                ConversionCategories.PRESSURE),
                                createConversion("atmosphere", "millimeter_of_mercury", BigDecimal.valueOf(760),
                                                ConversionCategories.PRESSURE),
                                createConversion("millimeter_of_mercury", "atmosphere", BigDecimal.valueOf(0.00131579),
                                                ConversionCategories.PRESSURE),
                                createConversion("atmosphere", "torr", BigDecimal.valueOf(760),
                                                ConversionCategories.PRESSURE),
                                createConversion("torr", "atmosphere", BigDecimal.valueOf(0.00131579),
                                                ConversionCategories.PRESSURE),

                                // Energy conversions
                                createConversion("joule", "kilojoule", BigDecimal.valueOf(0.001),
                                                ConversionCategories.ENERGY),
                                createConversion("kilojoule", "joule", BigDecimal.valueOf(1000),
                                                ConversionCategories.ENERGY),
                                createConversion("calorie", "joule", BigDecimal.valueOf(4.184),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "calorie", BigDecimal.valueOf(0.239006),
                                                ConversionCategories.ENERGY),
                                createConversion("watt_hour", "joule", BigDecimal.valueOf(3600),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "watt_hour", BigDecimal.valueOf(0.000277778),
                                                ConversionCategories.ENERGY),
                                createConversion("electronvolt", "joule", BigDecimal.valueOf(1.60218e-19),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "electronvolt", BigDecimal.valueOf(6.24151e+18),
                                                ConversionCategories.ENERGY),
                                createConversion("british_thermal_unit", "joule", BigDecimal.valueOf(1055.06),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "british_thermal_unit", BigDecimal.valueOf(0.000947817),
                                                ConversionCategories.ENERGY),
                                createConversion("kilocalorie", "joule", BigDecimal.valueOf(4184),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "kilocalorie", BigDecimal.valueOf(0.000239006),
                                                ConversionCategories.ENERGY),
                                createConversion("megajoule", "joule", BigDecimal.valueOf(1e6),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "megajoule", BigDecimal.valueOf(1e-6),
                                                ConversionCategories.ENERGY),
                                createConversion("gigajoule", "joule", BigDecimal.valueOf(1e9),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "gigajoule", BigDecimal.valueOf(1e-9),
                                                ConversionCategories.ENERGY),
                                createConversion("terajoule", "joule", BigDecimal.valueOf(1e12),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "terajoule", BigDecimal.valueOf(1e-12),
                                                ConversionCategories.ENERGY),
                                createConversion("watt_second", "joule", BigDecimal.valueOf(1),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "watt_second", BigDecimal.valueOf(1),
                                                ConversionCategories.ENERGY),
                                createConversion("kilowatt_hour", "joule", BigDecimal.valueOf(3.6e6),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "kilowatt_hour", BigDecimal.valueOf(2.77778e-7),
                                                ConversionCategories.ENERGY),
                                createConversion("megawatt_hour", "joule", BigDecimal.valueOf(3.6e9),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "megawatt_hour", BigDecimal.valueOf(2.77778e-10),
                                                ConversionCategories.ENERGY),
                                createConversion("gigawatt_hour", "joule", BigDecimal.valueOf(3.6e12),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "gigawatt_hour", BigDecimal.valueOf(2.77778e-13),
                                                ConversionCategories.ENERGY),
                                createConversion("terawatt_hour", "joule", BigDecimal.valueOf(3.6e15),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "terawatt_hour", BigDecimal.valueOf(2.77778e-16),
                                                ConversionCategories.ENERGY),
                                createConversion("foot_pound", "joule", BigDecimal.valueOf(1.35582),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "foot_pound", BigDecimal.valueOf(0.737562),
                                                ConversionCategories.ENERGY),
                                createConversion("erg", "joule", BigDecimal.valueOf(1e-7), ConversionCategories.ENERGY),
                                createConversion("joule", "erg", BigDecimal.valueOf(1e7), ConversionCategories.ENERGY),
                                createConversion("therm", "joule", BigDecimal.valueOf(1.05506e8),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "therm", BigDecimal.valueOf(9.47817e-9),
                                                ConversionCategories.ENERGY),
                                createConversion("horsepower_hour", "joule", BigDecimal.valueOf(2.68452e6),
                                                ConversionCategories.ENERGY),
                                createConversion("joule", "horsepower_hour", BigDecimal.valueOf(3.72506e-7),
                                                ConversionCategories.ENERGY),

                                // Power conversions
                                createConversion("watt", "kilowatt", BigDecimal.valueOf(0.001),
                                                ConversionCategories.POWER),
                                createConversion("kilowatt", "watt", BigDecimal.valueOf(1000),
                                                ConversionCategories.POWER),
                                createConversion("horsepower", "watt", BigDecimal.valueOf(745.7),
                                                ConversionCategories.POWER),
                                createConversion("watt", "horsepower", BigDecimal.valueOf(0.00134102),
                                                ConversionCategories.POWER),
                                createConversion("megawatt", "kilowatt", BigDecimal.valueOf(1000),
                                                ConversionCategories.POWER),
                                createConversion("kilowatt", "megawatt", BigDecimal.valueOf(0.001),
                                                ConversionCategories.POWER),
                                createConversion("kilovolt_ampere", "watt", BigDecimal.valueOf(1000),
                                                ConversionCategories.POWER),
                                createConversion("watt", "kilovolt_ampere", BigDecimal.valueOf(0.001),
                                                ConversionCategories.POWER),
                                createConversion("erg_per_second", "watt", BigDecimal.valueOf(1e-7),
                                                ConversionCategories.POWER),
                                createConversion("watt", "erg_per_second", BigDecimal.valueOf(1e+7),
                                                ConversionCategories.POWER),
                                createConversion("megawatt", "watt", BigDecimal.valueOf(1e6),
                                                ConversionCategories.POWER),
                                createConversion("watt", "megawatt", BigDecimal.valueOf(1e-6),
                                                ConversionCategories.POWER),
                                createConversion("gigawatt", "watt", BigDecimal.valueOf(1e9),
                                                ConversionCategories.POWER),
                                createConversion("watt", "gigawatt", BigDecimal.valueOf(1e-9),
                                                ConversionCategories.POWER),
                                createConversion("terawatt", "watt", BigDecimal.valueOf(1e12),
                                                ConversionCategories.POWER),
                                createConversion("watt", "terawatt", BigDecimal.valueOf(1e-12),
                                                ConversionCategories.POWER),
                                createConversion("milliwatt", "watt", BigDecimal.valueOf(0.001),
                                                ConversionCategories.POWER),
                                createConversion("watt", "milliwatt", BigDecimal.valueOf(1000),
                                                ConversionCategories.POWER),
                                createConversion("microwatt", "watt", BigDecimal.valueOf(1e-6),
                                                ConversionCategories.POWER),
                                createConversion("watt", "microwatt", BigDecimal.valueOf(1e6),
                                                ConversionCategories.POWER),
                                createConversion("nanowatt", "watt", BigDecimal.valueOf(1e-9),
                                                ConversionCategories.POWER),
                                createConversion("watt", "nanowatt", BigDecimal.valueOf(1e9),
                                                ConversionCategories.POWER),
                                createConversion("picowatt", "watt", BigDecimal.valueOf(1e-12),
                                                ConversionCategories.POWER),
                                createConversion("watt", "picowatt", BigDecimal.valueOf(1e12),
                                                ConversionCategories.POWER),
                                createConversion("femtowatt", "watt", BigDecimal.valueOf(1e-15),
                                                ConversionCategories.POWER),
                                createConversion("watt", "femtowatt", BigDecimal.valueOf(1e15),
                                                ConversionCategories.POWER),
                                createConversion("attowatt", "watt", BigDecimal.valueOf(1e-18),
                                                ConversionCategories.POWER),
                                createConversion("watt", "attowatt", BigDecimal.valueOf(1e18),
                                                ConversionCategories.POWER),
                                createConversion("decibel_milliwatt", "watt", BigDecimal.valueOf(0.00125893),
                                                ConversionCategories.POWER),
                                createConversion("watt", "decibel_milliwatt", BigDecimal.valueOf(795.7747),
                                                ConversionCategories.POWER),

                                // Force conversions
                                createConversion("newton", "kilonewton", BigDecimal.valueOf(0.001),
                                                ConversionCategories.FORCE),
                                createConversion("kilonewton", "newton", BigDecimal.valueOf(1000),
                                                ConversionCategories.FORCE),
                                createConversion("pound_force", "newton", BigDecimal.valueOf(4.44822),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "pound_force", BigDecimal.valueOf(0.224809),
                                                ConversionCategories.FORCE),
                                createConversion("dyne", "newton", BigDecimal.valueOf(0.00001),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "dyne", BigDecimal.valueOf(100000),
                                                ConversionCategories.FORCE),
                                createConversion("gram_force", "newton", BigDecimal.valueOf(0.00980665),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "gram_force", BigDecimal.valueOf(101.971621),
                                                ConversionCategories.FORCE),
                                createConversion("poundal", "newton", BigDecimal.valueOf(0.138255),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "poundal", BigDecimal.valueOf(7.23301),
                                                ConversionCategories.FORCE),
                                createConversion("kilopound_force", "newton", BigDecimal.valueOf(4448.22),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "kilopound_force", BigDecimal.valueOf(0.000224809),
                                                ConversionCategories.FORCE),
                                createConversion("ounce_force", "newton", BigDecimal.valueOf(0.2780139),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "ounce_force", BigDecimal.valueOf(3.596943),
                                                ConversionCategories.FORCE),
                                createConversion("ton_force", "newton", BigDecimal.valueOf(8896.443),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "ton_force", BigDecimal.valueOf(0.000112404),
                                                ConversionCategories.FORCE),
                                createConversion("kilogram_force", "newton", BigDecimal.valueOf(9.80665),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "kilogram_force", BigDecimal.valueOf(0.101971621),
                                                ConversionCategories.FORCE),
                                createConversion("millinewton", "newton", BigDecimal.valueOf(0.001),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "millinewton", BigDecimal.valueOf(1000),
                                                ConversionCategories.FORCE),
                                createConversion("micronewton", "newton", BigDecimal.valueOf(1e-6),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "micronewton", BigDecimal.valueOf(1e6),
                                                ConversionCategories.FORCE),
                                createConversion("nanonewton", "newton", BigDecimal.valueOf(1e-9),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "nanonewton", BigDecimal.valueOf(1e9),
                                                ConversionCategories.FORCE),
                                createConversion("piconewton", "newton", BigDecimal.valueOf(1e-12),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "piconewton", BigDecimal.valueOf(1e12),
                                                ConversionCategories.FORCE),
                                createConversion("femtonewton", "newton", BigDecimal.valueOf(1e-15),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "femtonewton", BigDecimal.valueOf(1e15),
                                                ConversionCategories.FORCE),
                                createConversion("attonewton", "newton", BigDecimal.valueOf(1e-18),
                                                ConversionCategories.FORCE),
                                createConversion("newton", "attonewton", BigDecimal.valueOf(1e18),
                                                ConversionCategories.FORCE),

                                // Angle conversions
                                createConversion("degree", "radian", BigDecimal.valueOf(0.0174533),
                                                ConversionCategories.ANGLE),
                                createConversion("radian", "degree", BigDecimal.valueOf(57.2958),
                                                ConversionCategories.ANGLE),
                                createConversion("gradian", "degree", BigDecimal.valueOf(0.9),
                                                ConversionCategories.ANGLE),
                                createConversion("degree", "gradian", BigDecimal.valueOf(1.11111),
                                                ConversionCategories.ANGLE),
                                createConversion("arcminute", "degree", BigDecimal.valueOf(0.0166667),
                                                ConversionCategories.ANGLE),
                                createConversion("degree", "arcminute", BigDecimal.valueOf(60),
                                                ConversionCategories.ANGLE),
                                createConversion("arcsecond", "degree", BigDecimal.valueOf(0.000277778),
                                                ConversionCategories.ANGLE),
                                createConversion("degree", "arcsecond", BigDecimal.valueOf(3600),
                                                ConversionCategories.ANGLE),
                                createConversion("radian", "gradian", BigDecimal.valueOf(63.662),
                                                ConversionCategories.ANGLE),
                                createConversion("gradian", "radian", BigDecimal.valueOf(0.0157079),
                                                ConversionCategories.ANGLE),
                                createConversion("radian", "arcminute", BigDecimal.valueOf(3437.75),
                                                ConversionCategories.ANGLE),
                                createConversion("arcminute", "radian", BigDecimal.valueOf(0.000290888),
                                                ConversionCategories.ANGLE),
                                createConversion("radian", "arcsecond", BigDecimal.valueOf(206265),
                                                ConversionCategories.ANGLE),
                                createConversion("arcsecond", "radian", BigDecimal.valueOf(4.84814e-6),
                                                ConversionCategories.ANGLE),
                                createConversion("gradian", "arcminute", BigDecimal.valueOf(54),
                                                ConversionCategories.ANGLE),
                                createConversion("arcminute", "gradian", BigDecimal.valueOf(0.0185185),
                                                ConversionCategories.ANGLE),
                                createConversion("gradian", "arcsecond", BigDecimal.valueOf(3240),
                                                ConversionCategories.ANGLE),
                                createConversion("arcsecond", "gradian", BigDecimal.valueOf(0.000308642),
                                                ConversionCategories.ANGLE),
                                createConversion("turn", "degree", BigDecimal.valueOf(360), ConversionCategories.ANGLE),
                                createConversion("degree", "turn", BigDecimal.valueOf(0.00277778),
                                                ConversionCategories.ANGLE),
                                createConversion("turn", "radian", BigDecimal.valueOf(6.28319),
                                                ConversionCategories.ANGLE),
                                createConversion("radian", "turn", BigDecimal.valueOf(0.159155),
                                                ConversionCategories.ANGLE),
                                createConversion("turn", "gradian", BigDecimal.valueOf(400),
                                                ConversionCategories.ANGLE),
                                createConversion("gradian", "turn", BigDecimal.valueOf(0.0025),
                                                ConversionCategories.ANGLE),
                                createConversion("turn", "arcminute", BigDecimal.valueOf(21600),
                                                ConversionCategories.ANGLE),
                                createConversion("arcminute", "turn", BigDecimal.valueOf(4.62963e-5),
                                                ConversionCategories.ANGLE),
                                createConversion("turn", "arcsecond", BigDecimal.valueOf(1.296e6),
                                                ConversionCategories.ANGLE),
                                createConversion("arcsecond", "turn", BigDecimal.valueOf(7.71605e-7),
                                                ConversionCategories.ANGLE),

                                // Frequency conversions
                                createConversion("gigahertz", "megahertz", BigDecimal.valueOf(1000),
                                                ConversionCategories.FREQUENCY),
                                createConversion("gigahertz", "revolutions_per_minute", BigDecimal.valueOf(6e10),
                                                ConversionCategories.FREQUENCY),
                                createConversion("gigahertz", "terahertz", BigDecimal.valueOf(0.001),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "attohertz", BigDecimal.valueOf(1e18),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "femtohertz", BigDecimal.valueOf(1e15),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "kilohertz", BigDecimal.valueOf(0.001),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "megahertz", BigDecimal.valueOf(1e-6),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "microhertz", BigDecimal.valueOf(1e6),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "millihertz", BigDecimal.valueOf(1000),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "nanohertz", BigDecimal.valueOf(1e9),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "picohertz", BigDecimal.valueOf(1e12),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "revolutions_per_minute", BigDecimal.valueOf(60),
                                                ConversionCategories.FREQUENCY),
                                createConversion("hertz", "terahertz", BigDecimal.valueOf(1e-12),
                                                ConversionCategories.FREQUENCY),
                                createConversion("kilohertz", "hertz", BigDecimal.valueOf(1000),
                                                ConversionCategories.FREQUENCY),
                                createConversion("kilohertz", "megahertz", BigDecimal.valueOf(0.001),
                                                ConversionCategories.FREQUENCY),
                                createConversion("kilohertz", "revolutions_per_minute", BigDecimal.valueOf(60000),
                                                ConversionCategories.FREQUENCY),
                                createConversion("kilohertz", "terahertz", BigDecimal.valueOf(1e-9),
                                                ConversionCategories.FREQUENCY),
                                createConversion("megahertz", "gigahertz", BigDecimal.valueOf(0.001),
                                                ConversionCategories.FREQUENCY),
                                createConversion("megahertz", "kilohertz", BigDecimal.valueOf(1000),
                                                ConversionCategories.FREQUENCY),
                                createConversion("megahertz", "revolutions_per_minute", BigDecimal.valueOf(6e7),
                                                ConversionCategories.FREQUENCY),
                                createConversion("megahertz", "terahertz", BigDecimal.valueOf(1e-6),
                                                ConversionCategories.FREQUENCY),
                                createConversion("revolutions_per_minute", "gigahertz", BigDecimal.valueOf(1.66667e-11),
                                                ConversionCategories.FREQUENCY),
                                createConversion("revolutions_per_minute", "hertz", BigDecimal.valueOf(0.0166667),
                                                ConversionCategories.FREQUENCY),
                                createConversion("revolutions_per_minute", "kilohertz",
                                                BigDecimal.valueOf(0.0000166667), ConversionCategories.FREQUENCY),
                                createConversion("revolutions_per_minute", "megahertz", BigDecimal.valueOf(1.66667e-8),
                                                ConversionCategories.FREQUENCY),
                                createConversion("revolutions_per_minute", "terahertz", BigDecimal.valueOf(1.66667e-14),
                                                ConversionCategories.FREQUENCY),
                                createConversion("terahertz", "gigahertz", BigDecimal.valueOf(1000),
                                                ConversionCategories.FREQUENCY),
                                createConversion("terahertz", "hertz", BigDecimal.valueOf(1e12),
                                                ConversionCategories.FREQUENCY),
                                createConversion("terahertz", "kilohertz", BigDecimal.valueOf(1e9),
                                                ConversionCategories.FREQUENCY),
                                createConversion("terahertz", "megahertz", BigDecimal.valueOf(1e6),
                                                ConversionCategories.FREQUENCY),
                                createConversion("terahertz", "revolutions_per_minute", BigDecimal.valueOf(6e13),
                                                ConversionCategories.FREQUENCY),

                                // Electric current conversions
                                createConversion("ampere", "milliampere", BigDecimal.valueOf(1000),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("milliampere", "ampere", BigDecimal.valueOf(0.001),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "kiloampere", BigDecimal.valueOf(0.001),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("kiloampere", "ampere", BigDecimal.valueOf(1000),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("microampere", "ampere", BigDecimal.valueOf(0.000001),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "microampere", BigDecimal.valueOf(1000000),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("kiloampere", "milliampere", BigDecimal.valueOf(1e6),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("milliampere", "kiloampere", BigDecimal.valueOf(1e-6),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("abampere", "ampere", BigDecimal.valueOf(10),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "abampere", BigDecimal.valueOf(0.1),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("nanoampere", "ampere", BigDecimal.valueOf(1e-9),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "nanoampere", BigDecimal.valueOf(1e9),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("picoampere", "ampere", BigDecimal.valueOf(1e-12),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "picoampere", BigDecimal.valueOf(1e12),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("femtoampere", "ampere", BigDecimal.valueOf(1e-15),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "femtoampere", BigDecimal.valueOf(1e15),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("attoampere", "ampere", BigDecimal.valueOf(1e-18),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "attoampere", BigDecimal.valueOf(1e18),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("gigaampere", "ampere", BigDecimal.valueOf(1e9),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "gigaampere", BigDecimal.valueOf(1e-9),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("teraampere", "ampere", BigDecimal.valueOf(1e12),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "teraampere", BigDecimal.valueOf(1e-12),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("megaampere", "ampere", BigDecimal.valueOf(1e6),
                                                ConversionCategories.ELECTRIC_CURRENT),
                                createConversion("ampere", "megaampere", BigDecimal.valueOf(1e-6),
                                                ConversionCategories.ELECTRIC_CURRENT));

                for (ConverterEntity conversion : conversions) {
                        if (!conversionRepository.existsByFromUnitAndToUnit(conversion.getFromUnit(),
                                        conversion.getToUnit())) {
                                conversionRepository.save(conversion);
                        }
                }

                if (!isUserInfoNull(List.of(username, adminEmail, adminPassword))) {
                        System.out.println(
                                        "\n\nAdmin user not created, perhaps you didn't set the env variables for it?\n\n");
                        return;
                }

                if (!userRepository.existsByEmailAndUsername(adminEmail, username)) {
                        RegisterDto registerDto = new RegisterDto(username, adminEmail, adminPassword, adminPassword);
                        createAdminUser(registerDto);
                } else {
                        System.out.println("\n\nAdmin user already exists, Email or Username already begin used\n\n");
                }
        }

        private ResponseEntity<Response<UserDto>> createAdminUser(RegisterDto registerDto) {
                return userController.create(registerDto, Roles.ROLE_ADMIN);
        }

        private Boolean isUserInfoNull(List<String> userInfo) {
                for (String info : userInfo) {
                        if (info == null || info.isEmpty()) {
                                System.out.println(
                                                "\n\nAdmin user info is missing, please provide the required information\n\n");
                                return false;
                        }
                }
                return true;
        }

        private ConverterEntity createConversion(String fromUnit, String toUnit, BigDecimal factor,
                        ConversionCategories type) {
                return ConverterEntity.builder()
                                .fromUnit(fromUnit)
                                .toUnit(toUnit)
                                .factor(factor)
                                .type(type)
                                .build();
        }
}